#!/bin/bash

sudo apt install -y docker-compose-plugin
docker compose version

cd ~
mkdir mosquitto
cd mosquitto

echo "listener 1883" > mosquitto.conf
echo "allow_anonymous true" >> mosquitto.conf

echo "services:" > docker-compose.yml
echo "  mosquitto:" >> docker-compose.yml
echo "    image: eclipse-mosquitto:latest" >> docker-compose.yml
echo "    container_name: mosquitto" >> docker-compose.yml
echo "    restart: always" >> docker-compose.yml
echo "    ports:" >> docker-compose.yml
echo "      - \"1883:1883\"" >> docker-compose.yml
echo "    volumes:" >> docker-compose.yml
echo "      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf" >> docker-compose.yml

docker compose up -d

