#!/bin/bash

sudo apt update
sudo apt upgrade -y
curl -sSL https://get.docker.com | sh

## replace with your linux user below (replace 'lvincek' with your user)
sudo usermod -aG docker $USER

sudo systemctl enable docker
sudo reboot now